parameters:
    # Sql relations classes
    ongr_connections.sql_relations.sql_relation.class: ONGR\ConnectionsBundle\Sync\Extractor\Relation\SqlRelation
    ongr_connections.sql_relations.table_relation.class: ONGR\ConnectionsBundle\Sync\Extractor\Relation\JoinStatement

