parameters:
    ongr_connections.import.source.class: ONGR\ConnectionsBundle\Event\ImportSourceEvent
    ongr_connections.import.modifier.class: ONGR\ConnectionsBundle\Event\ImportModifyEvent
    ongr_connections.import.consumer.class: ONGR\ConnectionsBundle\Event\ImportConsumeEvent
    ongr_connections.import.finish.class: ONGR\ConnectionsBundle\Event\ImportFinishEvent
    ongr_connections.import_data_directory.class: ONGR\ConnectionsBundle\Service\ImportDataDirectory
    ongr_connections.import_data_directory.data_dir: data

    # sync import pipeline event parent classes
    ongr_connections.sync.import.source.class: ONGR\ConnectionsBundle\Event\SyncImportSourceEvent
    ongr_connections.sync.import.modifier.class: ONGR\ConnectionsBundle\Event\SyncImportModifyEvent
    ongr_connections.sync.import.consumer.class: ONGR\ConnectionsBundle\Event\SyncImportConsumeEvent

services:
    ongr_connections.import_service:
        class: %ongr_connections.import_service.class%
        calls:
            - [ setPipelineFactory, [ @ongr_connections.pipeline_factory ] ]

    ongr_connections.import.source:
        class: %ongr_connections.import.source.class%

    ongr_connections.import.modifier:
        class: %ongr_connections.import.modifier.class%

    ongr_connections.import.consumer:
        class: %ongr_connections.import.consumer.class%

    ongr_connections.import.finish:
        class: %ongr_connections.import.finish.class%

    ongr_connections.import_data_directory:
        class: %ongr_connections.import_data_directory.class%
        arguments:
            - %kernel.root_dir%
            - %ongr_connections.import_data_directory.data_dir%
        calls:
            - [setDateHelper, [@ongr_connections.date_helper]]
