parameters:
    ongr_connections.import.source.class: ONGR\ConnectionsBundle\EventListener\ImportSourceEventListener
    ongr_connections.import.consumer.class: ONGR\ConnectionsBundle\EventListener\ImportConsumeEventListener
    ongr_connections.import.finish.class: ONGR\ConnectionsBundle\EventListener\ImportFinishEventListener
    ongr_connections.import_data_directory.class: ONGR\ConnectionsBundle\Service\ImportDataDirectory
    ongr_connections.import_data_directory.data_dir: data

    # sync import pipeline event parent classes
    ongr_connections.sync.execute.source.class: ONGR\ConnectionsBundle\EventListener\SyncExecuteSourceEventListener
    ongr_connections.sync.execute.consumer.class: ONGR\ConnectionsBundle\EventListener\SyncExecuteConsumeEventListener

services:
    ongr_connections.import_service:
        class: %ongr_connections.import_service.class%
        calls:
            - [ setPipelineFactory, [ @ongr_connections.pipeline_factory ] ]

    ongr_connections.import.source:
        class: %ongr_connections.import.source.class%

    ongr_connections.import.consumer:
        class: %ongr_connections.import.consumer.class%

    ongr_connections.import.finish:
        class: %ongr_connections.import.finish.class%

    ongr_connections.import_data_directory:
        class: %ongr_connections.import_data_directory.class%
        arguments:
            - %kernel.root_dir%
            - %ongr_connections.import_data_directory.data_dir%
        calls:
            - [setDateHelper, [@ongr_connections.date_helper]]
