parameters:
    ongr_connections.import.source.class: ONGR\ConnectionsBundle\Event\ImportSourceEvent
    ongr_connections.import.modifier.class: ONGR\ConnectionsBundle\Event\ImportModifyEvent
    ongr_connections.import.consumer.class: ONGR\ConnectionsBundle\Event\ImportConsumeEvent
    ongr_connections.import.finish.class: ONGR\ConnectionsBundle\Event\ImportFinishEvent

services:
    ongr_connections.import_service:
        class: %ongr_connections.import_service.class%
        calls:
            - [ setPipelineFactory, [ @ongr_connections.pipeline_factory ] ]

    ongr_connections.import.source:
        class: %ongr_connections.import.source.class%

    ongr_connections.import.modifier:
        class: %ongr_connections.import.modifier.class%

    ongr_connections.import.consumer:
        class: %ongr_connections.import.consumer.class%

    ongr_connections.import.finish:
        class: %ongr_connections.import.finish.class%
