parameters:
    ongr_connections.import_service.class: ONGR\ConnectionsBundle\Pipeline\PipelineStarter
    ongr_connections.import.source.class: ONGR\ConnectionsBundle\EventListener\ImportSourceEventListener
    ongr_connections.import.consumer.class: ONGR\ConnectionsBundle\EventListener\ImportConsumeEventListener
    ongr_connections.import.finish.class: ONGR\ConnectionsBundle\EventListener\ImportFinishEventListener

services:
    ongr_connections.import_service:
        class: %ongr_connections.import_service.class%
        calls:
            - [ setPipelineFactory, [ @ongr_connections.pipeline_factory ] ]

    ongr_connections.import.source:
        class: %ongr_connections.import.source.class%

    ongr_connections.import.modifier:
        class: %ongr_connections.import.modifier.class%

    ongr_connections.import.consumer:
        class: %ongr_connections.import.consumer.class%

    ongr_connections.import.finish:
        class: %ongr_connections.import.finish.class%
