parameters:
    ongr_connections.sync.table_manager.class: ONGR\ConnectionsBundle\Sync\DiffProvider\SyncJobs\TableManager
    ongr_connections.jobs_cleanup_service.class: ONGR\ConnectionsBundle\Sync\DiffProvider\SyncJobs\JobsCleanupService
    ongr_connections.sync.job_manager.class: ONGR\ConnectionsBundle\Sync\DiffProvider\SyncJobs\JobManager
    ongr_connections.sync.panther.storage_manager.mysql_storage_manager.class: ONGR\ConnectionsBundle\Sync\Panther\StorageManager\MysqlStorageManager
    ongr_connections.sync.panther.class: ONGR\ConnectionsBundle\Sync\Panther\Panther
    ongr_connections.mapping_listener.class: ONGR\ConnectionsBundle\EventListener\LoadClassMetadataListener
    ongr_connections.import_data_directory.class: ONGR\ConnectionsBundle\Service\ImportDataDirectory
    ongr_connections.import_data_directory.data_dir: data
    ongr_connections.date_helper.class: ONGR\ConnectionsBundle\Service\DateHelper
    ongr_connections.sync_task_complete_blocker_listener.class: ONGR\ConnectionsBundle\EventListener\SyncTaskCompleteBlockerListener
    ongr_connections.trigger_create_service.trigger_bundle_name: 'ONGRConnectionsBundle'
    ongr_connections.import_service.class: ONGR\ConnectionsBundle\Import\ImportService
    ongr_connections.sync.import_service.class: ONGR\ConnectionsBundle\Sync\SyncImportService

    ongr_connections.pipeline_factory.class: ONGR\ConnectionsBundle\Pipeline\PipelineFactory
    ongr_connections.pipeline_factory.pipeline_class: ONGR\ConnectionsBundle\Pipeline\Pipeline
    ongr_connections.sync.relations_collection.class: ONGR\ConnectionsBundle\Sync\Extractor\Relation\RelationsCollection
    ongr_connections.sync.data_sync_service.class: ONGR\ConnectionsBundle\Sync\DataSyncService
    ongr_connections.diff_provider.binlog_diff_provider.class: ONGR\ConnectionsBundle\Sync\DiffProvider\Binlog\BinlogDiffProvider
    ongr_connections.extractor.passthrough_extractor.class: ONGR\ConnectionsBundle\Sync\Extractor\PassthroughExtractor

    # Url invalidator service.
    ongr_connections.url_invalidator_service.class: ONGR\ConnectionsBundle\Service\UrlInvalidatorService
    ongr_connections.url_invalidator_service.cache_script: bin/varnish
    ongr_connections.url_invalidator_service.base_url: http://ongr.dev
    ongr_connections.url_invalidator_service.curl_timeout: 5

    ongr_connections.item_url_invalidator.class: ONGR\ConnectionsBundle\Service\AbstractItemUrlInvalidator

    # Import pipeline event parent classes.
    ongr_connections.import.source.class: ONGR\ConnectionsBundle\Event\ImportSourceEvent
    ongr_connections.import.modifier.class: ONGR\ConnectionsBundle\Event\ImportModifyEvent
    ongr_connections.import.consumer.class: ONGR\ConnectionsBundle\Event\ImportConsumeEvent
    ongr_connections.import.finish.class: ONGR\ConnectionsBundle\Event\ImportFinishEvent

    # Data sync pipeline event parent classes.
    ongr_connections.data_sync_source.class: ONGR\ConnectionsBundle\Event\DataSyncSourceEvent
    ongr_connections.data_sync_consume.class: ONGR\ConnectionsBundle\Event\DataSyncConsumeEvent

    # Binlog parameters.
    ongr_connections.sync.diff_provider.binlog_dir: /var/lib/mysql
    ongr_connections.sync.diff_provider.binlog_basename: mysql-bin

    # sync import pipeline event parent classes
    ongr_connections.sync.import.source.class: ONGR\ConnectionsBundle\Event\SyncImportSourceEvent
    ongr_connections.sync.import.modifier.class: ONGR\ConnectionsBundle\Event\SyncImportModifyEvent
    ongr_connections.sync.import.consumer.class: ONGR\ConnectionsBundle\Event\SyncImportConsumeEvent

services:
    ongr_connections.sync.table_manager:
        class: %ongr_connections.sync.table_manager.class%
        # Arguments are injected in bundle Extension class.

    ongr_connections.sync.panther.storage_manager.mysql_storage_manager:
        class: %ongr_connections.sync.panther.storage_manager.mysql_storage_manager.class%
        # Arguments are injected in bundle Extension class.

    ongr_connections.sync.panther:
        class: %ongr_connections.sync.panther.class%
        # Arguments are injected in bundle Extendion class.

    ongr_connections.jobs_cleanup_service:
        class: %ongr_connections.jobs_cleanup_service.class%

    ongr_connections.sync.job_manager:
        class: %ongr_connections.sync.job_manager.class%
        arguments:
            - @doctrine.orm.entity_manager
            - 'ONGRConnectionsBundle:' # Extension replaces this argument with value from config.
        calls:
            - [setLogger, [@?logger]]
        tags:
            - { name: ongr_connections.sync.job_manager, type: default }
            - { name: monolog.logger, channel: sync }

    ongr_connections.mapping_listener:
        class: %ongr_connections.mapping_listener.class%
        tags:
            - { name: doctrine.event_listener, event: loadClassMetadata }

    ongr_connections.pipeline.abstract:
        class: ONGR\ConnectionsBundle\Pipeline\Pipeline
        abstract: true
        calls:
            - [ setDispatcher, [ @event_dispatcher ] ]
    ongr_connections.import_data_directory:
        class: %ongr_connections.import_data_directory.class%
        arguments:
            - %kernel.root_dir%
            - %ongr_connections.import_data_directory.data_dir%
        calls:
            - [setDateHelper, [@ongr_connections.date_helper]]

    ongr_connections.date_helper:
        class: %ongr_connections.date_helper.class%

    ongr_connections.sync_task_complete_blocker_listener:
        class: %ongr_connections.sync_task_complete_blocker_listener.class%
        tags:
            - { name: kernel.event_listener, event: ongr_connections.sync_task_complete, method: handleEvent }

    ongr_connections.pipeline_factory:
        class: %ongr_connections.pipeline_factory.class%
        calls:
            - [ setDispatcher, [ @event_dispatcher ] ]
            - [ setClassName, [ %ongr_connections.pipeline_factory.pipeline_class% ] ]

    ongr_connections.url_invalidator_service:
        class: %ongr_connections.url_invalidator_service.class%
        arguments:
            - @router
            - @es.manager
            - %ongr_connections.url_invalidator_service.base_url%
            - %ongr_connections.url_invalidator_service.curl_timeout%
            - %kernel.root_dir%
            - %ongr_connections.url_invalidator_service.cache_script%

    ongr_connections.item_url_invalidator:
        class: %ongr_connections.url_invalidator_service.class%
        arguments:
            - @router
            - @es.manager
            - %ongr_connections.url_invalidator_service.base_url%
            - %ongr_connections.url_invalidator_service.curl_timeout%
            - %kernel.root_dir%
            - %ongr_connections.url_invalidator_service.cache_script%

    ongr_connections.sync.relations_collection:
        class: %ongr_connections.sync.relations_collection.class%

    ongr_connections.sync.doctrine_extractor:
        class: ONGR\ConnectionsBundle\Sync\Extractor\DoctrineExtractor
        calls:
            - [ setRelationsCollection, [ @ongr_connections.sync.relations_collection ] ]
            - [ setConnection, [ @database_connection ] ]

    ongr_connections.import_service:
        class: %ongr_connections.import_service.class%
        calls:
            - [ setPipelineFactory, [ @ongr_connections.pipeline_factory ] ]

    ongr_connections.sync.import_service:
        class: %ongr_connections.sync.import_service.class%
        calls:
            - [ setPipelineFactory, [ @ongr_connections.pipeline_factory ] ]

    ongr_connections.import.source:
        class: %ongr_connections.import.source.class%

    ongr_connections.import.modifier:
        class: %ongr_connections.import.modifier.class%

    ongr_connections.import.consumer:
        class: %ongr_connections.import.consumer.class%

    ongr_connections.import.finish:
        class: %ongr_connections.import.finish.class%

    ongr_connections.sync.diff_provider.binlog_diff_provider:
        class: %ongr_connections.diff_provider.binlog_diff_provider.class%
        arguments:
            - @database_connection
            - %ongr_connections.sync.diff_provider.binlog_dir%
            - %ongr_connections.sync.diff_provider.binlog_basename%

    ongr_connections.sync.extractor.passthrough_extractor:
        class: %ongr_connections.extractor.passthrough_extractor.class%

    ongr_connections.sync.data_sync_service:
        class: %ongr_connections.sync.data_sync_service.class%
        calls:
            - [ setPipelineFactory, [ @ongr_connections.pipeline_factory ] ]

    ongr_connections.sync.import.source:
        class: %ongr_connections.sync.import.source.class%

    ongr_connections.sync.import.modifier:
        class: %ongr_connections.sync.import.modifier.class%

    ongr_connections.sync.import.consumer:
        class: %ongr_connections.sync.import.consumer.class%

    ongr_connections.sync.import.finish:
        class: %ongr_connections.import.finish.class%
