language: php
php:
  - 5.4
  - 5.5
  - 5.6
env:
  - PREFER_LOWEST="--prefer-lowest" SYMFONY="2.6.*"
  - PREFER_LOWEST="" SYMFONY="2.6.*"
services:
  - elasticsearch
install:
  - sudo pip install -q sphinx --use-mirrors
  - wget -q -O conf.py https://raw.githubusercontent.com/ongr-io/docs-aggregator/master/source/conf-travis.py
  - mkdir _static
  - composer require --no-update symfony/symfony:${SYMFONY}
before_install:
  # SQL settings
  - sudo chmod 0644 /etc/mysql/my.cnf
  - sudo sed "/skip-external-locking/a log-bin=mysql-bin\nbinlog_format = ROW\ndatadir = /var/lib/mysql" -i /etc/mysql/my.cnf
  - sudo cat /etc/mysql/my.cnf
  - sudo usermod -g travis mysql
  - sudo chmod -R 0777 /var/lib/mysql
  - sudo service mysql restart
before_script:
  - composer self-update
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('root') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
  - composer update --prefer-source $PREFER_LOWEST
script:
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover
  - vendor/bin/phpcs -p --standard=$TRAVIS_BUILD_DIR/vendor/ongr/ongr-strict-standard/ONGR --ignore=vendor/,Tests/app/,Resources/public/,Sync/DiffProvider/DiffProvider.php,Sync/DiffProvider/Item/BaseDiffItem.php ./
  - sphinx-build -nWq -b html -c . Resources/doc _build/html
after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && wget --post-data="" -q -O /dev/null http://readthedocs.org/build/ongr'
cache:
  directories:
    - vendor/
    - $HOME/.composer/cache
